name: Blueprint Pages

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    uses: leanprover/verso-blueprint/.github/workflows/blueprint-pages.yml@af54e3eedd11e4a7604544712e70d447b6dc55aa
    with:
      checkout_submodules: true
      harness_enabled: true
      warm_dependency_cache: true
    secrets: inherit
