name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lean
        uses: leanprover/lean-action@v1
        with:
          auto-config: false

      - name: Pre-build step
        run: ./scripts/pre-build.sh

      - name: Build default Lake targets
        uses: leanprover/lean-action@v1

      - name: Build blueprint page
        run: ./scripts/build-page.sh